const bcrypt = require('bcryptjs');
const admins = [
  {
    name: 'Ygpdeb N.',
    image: 'https://i.ibb.co/ZTWbx5z/team-1.jpg',
    email: 'ygpdeb@gmail.com',
    password: bcrypt.hashSync('Yygpdeb3$'),
    phone: '0660-5670-774',
    role: 'Networking',
    joiningData: new Date(),
  },
  {
    name: 'Ygpdeb D.',
    image: 'https://i.ibb.co/d294W8Y/team-4.jpg',
    email: 'ygpdeb@gmail.com',
    password: bcrypt.hashSync('Ygpdeb2$'),
    phone: '0681-848-08800',
    role: 'Security Data',
    joiningData: new Date(),
  },
  {
    name: 'Iulian G.',
    image: 'https://i.ibb.co/m5B0hK4/team-8.jpg',
    email: 'ghepes.julian@gmail.com',
    password: bcrypt.hashSync('Iiulian2$'),
    phone: '708-488-9728',
    role: 'IT',
    joiningData: new Date(),
  },
  {
    name: 'Ghepes I.',
    image: 'https://i.ibb.co/SNN7JCX/team-6.jpg',
    email: 'ghepes.julian@gmail.com',
    password: bcrypt.hashSync('Iiulian1$'),
    phone: '+43/0660-567-0774',
    role: 'Accountant',
    joiningData: new Date(),
  },
  {
    name: 'Ygpdeb M.',
    image: 'https://i.ibb.co/GWVWYNn/team-7.jpg',
    email: 'ygpdeb@gmail.com',
    password: bcrypt.hashSync('Yygpdeb1$'),
    phone: '0681-8480-8800',
    role: 'Manager',
    joiningData: new Date(),
  },
  {
    name: 'Simiyoo T.',
    image: 'https://i.ibb.co/XjwBLcK/team-2.jpg',
    email: 'info.simiyoo@gmail.com',
    password: bcrypt.hashSync('Simiyoo1$'),
    phone: '+49/01743-544-5845',
    role: 'CEO',
    joiningData: new Date(),
  },
  {
    name: 'Iulian Ghepes',
    image: 'https://i.ibb.co/3zs3H7z/team-5.jpg',
    email: 'julian.gheny@gmail.com',
    password: bcrypt.hashSync('*/Jjulian1$'),
    phone: '+43/660-633-6832',
    role: 'Admin',
    joiningData: new Date(),
  },
  {
    name: 'Administrator Team Wromo',
    image: 'https://i.ibb.co/WpM5yZZ/9.png',
    email: 'info.wromo@gmail.com',
    password: bcrypt.hashSync('*/Wromo1$'),
    phone: '0660-633-6832',
    role: 'Admin',
    joiningData: new Date(),
  },
];

module.exports = admins;
